include: package:flutter_lints/flutter.yaml

linter:
  rules:
  - avoid_classes_with_only_static_members
  - avoid_catching_errors
  - avoid_empty_else
  - avoid_init_to_null
  - avoid_null_checks_in_equality_operators
  - avoid_positional_boolean_parameters
  - avoid_redundant_argument_values
  - avoid_relative_lib_imports
  - avoid_return_types_on_setters
  - avoid_shadowing_type_parameters
  - avoid_single_cascade_in_expression_statements
  - avoid_types_as_parameter_names
  - avoid_unused_constructor_parameters
  - avoid_void_async
  - avoid_web_libraries_in_flutter
  - camel_case_extensions
  - cancel_subscriptions
  - close_sinks
  - control_flow_in_finally
  - curly_braces_in_flow_control_structures
  - empty_catches
  - empty_constructor_bodies
  - empty_statements
  - file_names
  - hash_and_equals
  - implementation_imports
  - no_duplicate_case_values
  - null_closures
  - prefer_adjacent_string_concatenation
  - prefer_collection_literals
  - prefer_conditional_assignment
  - prefer_const_constructors
  - prefer_const_constructors_in_immutables
  - prefer_const_declarations
  - prefer_expression_function_bodies
  - prefer_final_fields
  - prefer_final_locals
  - prefer_function_declarations_over_variables
  - prefer_if_null_operators
  - prefer_inlined_adds
  - prefer_int_literals
  - prefer_is_empty
  - prefer_is_not_empty
  - prefer_iterable_whereType
  - prefer_null_aware_operators
  - prefer_single_quotes
  - prefer_spread_collections
  - prefer_typing_uninitialized_variables
  - sort_constructors_first
  - sort_unnamed_constructors_first
  - test_types_in_equals
  - unnecessary_brace_in_string_interps
  - unnecessary_const
  - unnecessary_lambdas
  - unnecessary_new
  - unnecessary_null_in_if_null_operators
  - unnecessary_overrides
  - unnecessary_this
  - use_full_hex_values_for_flutter_colors
  - use_function_type_syntax_for_parameters
  - use_key_in_widget_constructors
  - use_rethrow_when_possible
  - use_string_buffers
  - use_to_and_as_if_applicable
  - avoid_print
  - avoid_type_to_string
  - discarded_futures
  - prefer_void_to_null
  - unsafe_html
  - always_declare_return_types
  - avoid_catches_without_on_clauses
  - avoid_unnecessary_containers
  - avoid_multiple_declarations_per_line
  - sized_box_shrink_expand
  - slash_for_doc_comments
  - unnecessary_getters_setters
  - unnecessary_late
  - use_decorated_box
  - use_colored_box
  - use_enums
  - public_member_api_docs
